openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  /:
    post:
      summary: Index
      operationId: index__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BodyRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    BodyRequest:
      title: BodyRequest
      required:
        - body
      type: object
      properties:
        body:
          title: Body
          type: string
        skip_validation:
          title: Skip Validation
          type: boolean
          default: false
        email:
          title: Email
          type: string
          default: ''
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
